import { StyleSheet } from "react-native";
import { colors, fonts, fontSizes, spacing } from "../../../../constants/theme";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.white,
    padding: spacing.md,
  },
  center: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
  },
  loadingText: {
    marginTop: 8,
    color: colors.textSecondary,
    fontFamily: fonts.medium,
  },
  text: {
    fontFamily: fonts.medium,
    fontSize: fontSizes.body,
    color: colors.textSecondary,
  },
  card: {
    backgroundColor: colors.grayLight,
    borderRadius: 12,
    padding: spacing.md,
    marginBottom: spacing.md,
    borderWidth: 1,
    borderColor: colors.graySoft,
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: spacing.sm,
  },
  cardTitle: {
    fontFamily: fonts.bold,
    color: colors.textPrimary,
    fontSize: fontSizes.body,
  },
  fechaText: {
    color: colors.textSecondary,
    fontSize: fontSizes.small,
    fontFamily: fonts.regular,
  },
  estadoBox: {
    backgroundColor: "#2563EB",
    borderRadius: 10,
    paddingVertical: 4,
    paddingHorizontal: 8,
    alignItems: "center",
    justifyContent: "center",
  },
  estadoText: {
    color: colors.white,
    fontSize: fontSizes.xtraSmall,
    fontFamily: fonts.medium,
  },
  totalText: {
    marginTop: spacing.xs,
    marginBottom: spacing.sm,
    color: colors.textPrimary,
    fontFamily: fonts.regular,
    fontSize: fontSizes.body,
  },
  bold: {
    fontFamily: fonts.medium,
  },
  productList: {
    marginTop: spacing.xs,
    marginBottom: spacing.sm,
  },
  productItem: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 4,
  },
  productText: {
    fontFamily: fonts.regular,
    fontSize: fontSizes.small,
    color: colors.textPrimary,
  },
  btnEntregado: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#16A34A",
    borderRadius: 10,
    paddingVertical: spacing.sm,
    gap: 6,
    marginTop: spacing.sm,
  },
  btnText: {
    color: colors.white,
    fontFamily: fonts.medium,
    fontSize: fontSizes.small,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.5)",
    justifyContent: "center",
    alignItems: "center",
  },
  modalContent: {
    backgroundColor: colors.white,
    padding: spacing.lg,
    borderRadius: 14,
    width: "88%",
    elevation: 6,
    shadowColor: "#000",
    shadowOpacity: 0.25,
    shadowRadius: 6,
  },
  modalTitle: {
    fontSize: fontSizes.subtitle,
    fontFamily: fonts.bold,
    color: colors.textPrimary,
    textAlign: "center",
    marginBottom: spacing.sm,
  },
  modalText: {
    fontSize: fontSizes.body,
    color: colors.textSecondary,
    textAlign: "center",
    fontFamily: fonts.medium,
    marginBottom: spacing.sm,
  },
  modalLabel: {
    fontFamily: fonts.medium,
    fontSize: fontSizes.small,
    color: colors.textPrimary,
    textAlign: "center",
    marginTop: spacing.sm,
    marginBottom: spacing.xs,
  },
  input: {
    borderWidth: 1,
    borderColor: colors.graySoft,
    borderRadius: 10,
    paddingVertical: spacing.sm,
    textAlign: "center",
    fontFamily: fonts.medium,
    fontSize: fontSizes.body,
    color: colors.textPrimary,
    marginVertical: spacing.sm,
  },
  optionRow: {
    flexDirection: "row",
    justifyContent: "space-around",
    marginVertical: spacing.md,
  },
  option: {
    paddingVertical: spacing.sm,
    paddingHorizontal: spacing.md,
    borderRadius: 10,
    backgroundColor: colors.grayLight,
    alignItems: "center",
    minWidth: 90,
  },
  optionSelected: {
    backgroundColor: colors.primary,
  },
  optionText: {
    fontFamily: fonts.medium,
    fontSize: fontSizes.small,
    color: colors.textPrimary,
  },
  optionTextSelected: {
    color: colors.white,
  },
  modalButtons: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: spacing.md,
  },
  btnCancelar: {
    flex: 1,
    backgroundColor: colors.graySoft,
    borderRadius: 10,
    paddingVertical: spacing.sm,
    marginRight: spacing.sm,
    alignItems: "center",
  },
  btnConfirmar: {
    flex: 1,
    backgroundColor: colors.green,
    borderRadius: 10,
    paddingVertical: spacing.sm,
    marginLeft: spacing.sm,
    alignItems: "center",
  },
  btnCancelarText: {
    fontFamily: fonts.medium,
    fontSize: fontSizes.small,
    color: colors.textPrimary,
  },
  btnConfirmarText: {
    fontFamily: fonts.medium,
    fontSize: fontSizes.small,
    color: colors.white,
  },
  
});
